### ISSUE TITLE
I can't go back to the main view using browser arrow ;P (iPhone 6)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#100]
![untitled design](https://user-images.githubusercontent.com/28931514/27610611-56bdb616-5b8f-11e7-9a7e-170503a546b1.png)

**Comment by michalmikolajczyk** [comment]
UPDATE: this is a bug that has been around since the release. The effects I noticed:
– the native bar stops responding (not with #93 tho)
– scroll becomes unresponsive, but the buttons and links on the page work

It is simple to reproduce the bug, it happens after navigating from main page to offer

**Comment by jonzee** [comment]
@lam3lka did you try this on latest version (on production)? what is your browser version? I tried this on my devices (iPhone 4s, Samsung S3, Shrome/Safari) and I hadn't any problems with back button.

**Comment by lam3lka** [comment]
On my tablet is ok right now. I just need to check it on mobile but I think it works properly now.

**Comment by lam3lka** [comment]
Działa!
