### ISSUE TITLE
Searching by motorcycle type is not working

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#105]
![19551286_1546948918690237_1104416375_n](https://user-images.githubusercontent.com/28931514/27654379-5b42a1e8-5c42-11e7-9ad8-7fa8da0478c0.jpg)

**Comment by jonzee** [comment]
ok, we need to know what types of motorcycles we want to filter, I'll send you actual list

**Comment by lam3lka** [comment]
today, (need to consult it with Michal)

**Comment by lam3lka** [comment]
We decided to do not change filters in a main view. We are adding a general category to the offer view - bike owners need to choose this general category for their motorcycles when they add an offer.

**Comment by jonzee** [comment]
done in #114

**Comment by lam3lka** [comment]
Oki, tylko kilka pytań:

1. Dlaczego skuter nie pojawia się też przy wyszukiwaniu za pomocą filtra "street"?
2. Dlaczego Husaberg nie jest przy wyszukiwaniu za pomocą filtra "off-road"?

**Comment by jonzee** [comment]
ad 1. skuter ma kategorię `scooter`
ad 2. husaberg ma kategorię `dual-sport`
Ogólnie nie przywiązuje się do tych kategorii (można to łatwo zmienić w PSequel), kwestia jest taka, że każdy motocykl może mieć jedną kategorię (street, off-road) i jedną podkategorię (naked, scrambler)
