### ISSUE TITLE
No confirmation e-mail with booking details

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#106]

**Comment by jonzee** [comment]
@lam3lka I'm gonna need some copy/email template for this

**Comment by lam3lka** [comment]
I will do that today

**Comment by lam3lka** [comment]
https://docs.google.com/a/vikinggarage.com/document/d/1sg-1qA4WyQoZzHhIlJdRo1yjqxkBzGY6huEzopiKYg8/edit?usp=sharing copy na samym końcu (@jonzee jakby co to też proszę o feedback)

**Comment by jonzee** [comment]
@lam3lka I need english version as well

**Comment by lam3lka** [comment]
done

**Comment by jonzee** [comment]
@lam3lka I need copy for other subpages (bike owners, guides, mechanics)

**Comment by lam3lka** [comment]
here: https://docs.google.com/a/vikinggarage.com/document/d/1sg-1qA4WyQoZzHhIlJdRo1yjqxkBzGY6huEzopiKYg8/edit?usp=sharing

**Comment by lam3lka** [comment]
It's working we just need to change e-mails (e-mail we are going to use: ride@vikinggarage.com  and contact@vikinggarage.com )

**Comment by michalmikolajczyk** [comment]
this seems to depend on issue #79 

- [ ] please fill in the correct data into `app.json` and `env` files
- [ ] update README

**Comment by jonzee** [comment]
done in #126

**Comment by michalmikolajczyk** [comment]
🥇
