### ISSUE TITLE
Blue background > Photo (Safari)

### ISSUE THREAD

**Issue by Malwix** [michalmikolajczyk/viking-garage-frontend#107]
Nadal tlo jest lekko niebeiskie na zdjeciu moto- tylko w Safari i u mnie, u Asi jest ok.

![screen shot 2017-06-28 at 20 44 18](https://user-images.githubusercontent.com/29760601/27655169-b4225e32-5c44-11e7-935c-78dede2a380d.png)

**Comment by jonzee** [comment]
@Malwix could you prepare new photo (without background), put it in drive and ping me?

**Comment by Malwix** [comment]
@jonzee photos done, donfirm if ok

**Comment by Malwix** [comment]
@jonzee wyprobuj te z Asany nie Google Drive. Link na Slacku.

**Comment by jonzee** [comment]
@Malwix wrzuciłem zdjęcia z asany

**Comment by Malwix** [comment]
Nadal widze lekko niebieskie tlo... Wrzucilam na Asane pliki PNG naszych 3 moto, mam nadzieje ze pojdzie. Zastanawiam sie czy to kwestia ustawien w moim kompie....

https://app.asana.com/0/335209227742518/370626690286007

**Comment by jonzee** [comment]
@Malwix ok, wrzuciłem na stronę

**Comment by lam3lka** [comment]
@Malwix i jak się to teraz prezentuje?

**Comment by Malwix** [comment]
@jonzee prezentuje sie bdb :) nasze sa bialutkie jak snieg. Poprawilam fotki wypozyczalni- sa teraz bez tla + w formacie PNG + dostepne na Drive.

https://drive.google.com/drive/u/0/folders/0B2t9Gc1TyaXSVnRNbDRNOHB6MHM

**Comment by jonzee** [comment]
@Malwix wrzucone, proszę o check i zamknięcie issue
