### ISSUE TITLE
Where is motorcycle description?? (mobile)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#108]
![19576909_10209860843462288_1701079235_o](https://user-images.githubusercontent.com/28931514/27655965-99c52f94-5c47-11e7-8b9d-01758a554f0e.png)
Malwa needs to add motorcycle description to the graphics for mobile.

**Comment by jonzee** [comment]
@Malwix I need some tips how to arrange this

**Comment by Malwix** [comment]
@jonzee please add moto description between "Ride" button and details- do you need the design?
