### ISSUE TITLE
Dialog Offer > Submit button 

### ISSUE THREAD

**Issue by Malwix** [michalmikolajczyk/viking-garage-frontend#110]
Przycisk "Submit" powinien byc czerwony a napis baly, tak smao jak "Ride".

![screen shot 2017-06-28 at 20 52 35](https://user-images.githubusercontent.com/29760601/27656216-779900c0-5c48-11e7-8bee-a8a1ed7da55f.png)

**Comment by Malwix** [comment]
@jonzee niestety jest nadal szary i jak najezdzam kursorem to sie pokazuje kolko przekreslone... 

![screen shot 2017-07-05 at 00 46 34](https://user-images.githubusercontent.com/29760601/27843995-865e9a5c-611b-11e7-8cef-44db8e4ab3af.png)

**Comment by jonzee** [comment]
@Malwix tak, przycisk jest nieaktywny dopóki użytkownik nie wpisze imienia i maila - taki też działa material-ui, po wpisaniu danych przycisk jest czerwony z białym napisem

**Comment by Malwix** [comment]
ah to przepraszam
