### ISSUE TITLE
The letter R in the RIDE button, should be the rune Raido

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#112]
jako dowolny użytkownik,
gdy otworzę stronę główną
i przejdę do widoku oferty,
to na przycisku RIDE nie widzę runy Raido

**Comment by jonzee** [comment]
it's according to the newest design, discuss this with @Malwix please

**Comment by Malwix** [comment]
@jonzee please change "R" into white Raido

**Comment by Malwix** [comment]
Jest :)
