### ISSUE TITLE
New photo of Honda SuperSound

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#116]
To zdjęcie Hondy jest rozjechane - rozpikselowane i dziwnie krzywe

**Comment by michalmikolajczyk** [comment]
@Malwix co z tym?

**Comment by Malwix** [comment]
@michalmikolajczyk zrobie to dzisiaj

**Comment by Malwix** [comment]
@jonzee poprawiony plik na Asanie (tam gdzie KTMy)

**Comment by jonzee** [comment]
@lam3lka wrzucone, oceń czy ok
