### ISSUE TITLE
Margin should be the same for text on page

### ISSUE THREAD

**Issue by Malwix** [michalmikolajczyk/viking-garage-frontend#120]
@jonzee margines powinien byc taki sam jesli chodzi o opis moto, tabelke z generalnym info oraz info dot. wlasciciela, bo inaczej to jednak jest balagan w obrazie

![screen shot 2017-07-05 at 01 13 37](https://user-images.githubusercontent.com/29760601/27844347-bb0b8e0e-6120-11e7-8bcd-f25758e2f24c.png)

**Comment by Malwix** [comment]
Marginesy super :) ale tableka po srodku sie za bardzo skleila, info na siebie nachodzi- musi byc podzial jak na poprzedniej fotce.

Ponizej jest widok aktualny, w ktorym info na siebie nachodzi:

![screen shot 2017-07-06 at 22 50 21](https://user-images.githubusercontent.com/29760601/27932360-cfb6b490-629d-11e7-8bdb-734e1fde2c58.png)

**Comment by jonzee** [comment]
@Malwix fixed, pls checkout

**Comment by jonzee** [comment]
it's done, reviewed, pls checkout on staging

**Comment by lam3lka** [comment]
tutaj jeszcze coś nierówno: 

<img width="873" alt="zrzut ekranu 2017-07-13 o 14 25 19" src="https://user-images.githubusercontent.com/28931514/28166311-b29ebef4-67d7-11e7-8a24-69bd46ea73d1.png">

**Comment by jonzee** [comment]
@lam3lka good point, I didn't find this case, fixed in #129

**Comment by Malwix** [comment]
Perfect! :)
