### ISSUE TITLE
GROUPON subpage (new feature)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#127]
Jako dowolny użytkownik,
gdy otworzę stronę główną 
i kliknę w menu GROUPON 
chcę przejść do podstrony, która będzie zawierać wszystkie informacje niezbędne do realizacji GROUPONu

Link to copy: https://docs.google.com/document/d/1_LjGxwpBLn7GrRIGUVGLy2mTfdN18gQC8pJvcmNeNp8/edit

**Comment by jonzee** [comment]
@lam3lka do we need english version? @Malwix pls assign me when design will be ready

**Comment by Malwix** [comment]
@jonzee design is ready, available on Google drive:

https://drive.google.com/drive/u/0/folders/0B0N2oBFX4TZRT3ZSWGpIUHRWRFE
