### ISSUE TITLE
booking view (new feature)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#128]
Jako dowolny użytkownik,
gdy otworzę stronę z widokiem oferty
i przejdę do rezerwacji motocykla,
to chcę dokonać rezerwacji na wybrany dzień i wybraną liczbę godzin zgodną z moim kuponem GROUPON.

**Comment by Malwix** [comment]
@jonzee Widoki gotowe dla desktopu i mobi (oraz szkielety). Pliki dostepne na google Drive:

https://drive.google.com/drive/u/0/folders/0B3nSf0TR_aGSTWJlYUlnSGZxNmc

**Comment by michalmikolajczyk** [comment]
I believe this is covered by the #158
