### ISSUE TITLE
GROUPON main page view

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#131]
Jako użytkownik przekierowany ze strony GROUPON,
gdy wchodzę na stronę główną www.vikinggarage.com
chcę wiedzieć, które motocykle mogę zarezerwować do jazdy ze zniżką GROUPON.

**Comment by Malwix** [comment]
@jonzee zdjecia z updatem logo Groupona dostepne na Google Drive (folder Groupon).

https://drive.google.com/drive/u/0/folders/0B3nSf0TR_aGSTWJlYUlnSGZxNmc

**Comment by lam3lka** [comment]
Co z tym? 
Oznaczmy oferty z GROUPON logotypem GROUPON.
