### ISSUE TITLE
Edit Privacy Policy

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#134]
Janek, zmniejsz proszę te śródtytuły pomiędzy akapitami ;)

**Comment by jonzee** [comment]
done in #155

**Comment by michalmikolajczyk** [comment]
nie, tam pozostało jeszcze jedno

czy ktoś może zmienić ten tekst wyboldowany "children under the age of 13", bo stawia nas w kiepskim świetle? Wystarczy np. "Age restrictions"

<img width="1680" alt="screen shot 2017-07-19 at 10 59 47 am" src="https://user-images.githubusercontent.com/1655227/28359105-7768a3f6-6c71-11e7-83d4-15343bbe479c.png">

**Comment by jonzee** [comment]
added commit in #155
