### ISSUE TITLE
Offers listing

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#144]
Jako użytkownik strony, 
gdy wejdę na stronę główną
chcę widzieć 8 wyświetlanych ofert 
(nieparzysta liczba źle działa na moje zmysły estetyczne).

**Comment by jonzee** [comment]
Ok, there is env var `VG_LIMIT` on frontend and backend to set pagination limit but I have to add this to documentation!

**Comment by jonzee** [comment]
fixed in #154
