### ISSUE TITLE
Mike's bikes – hourly price

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#151]
As an owner,
I want my offers visible on VG
and I want the offers to display
the lowest hourly price
instead of the highest daily price

**Comment by jonzee** [comment]
[ ] implemented hour units for groupon, off-road & dual-sport motorbikes
[ ] updated staging prices data base

**Comment by michalmikolajczyk** [comment]
all hourly prices should be set to `233` for now

**Comment by jonzee** [comment]
ok, `233` set on staging db

**Comment by michalmikolajczyk** [comment]
let me know when prod is updated pls

**Comment by michalmikolajczyk** [comment]
done
