### ISSUE TITLE
Better photos

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#152]
As an owner
I would like my bikes to have relevant photos
and perhaps also my own photos

we can actually do an A/B test to see if stock photos get better reactions over our private photos

**Comment by michalmikolajczyk** [comment]
bump

**Comment by lam3lka** [comment]
I added relevant photos and I double checked photos in offerts. Rafał from Abacus said that he always have problems with photos, so we could do A/B tests on our motorcycles and with new offerts (like the new ones from Moto 71 - Rental from Wrocław)

**Comment by lam3lka** [comment]
I think the option to add more photos to offer is needed - it can help an offerer show his product and it will increase reliability of our offerers and VG

**Comment by michalmikolajczyk** [comment]
Nope, the ktm 125 sx and Husaberg have incorrect photos (different model years)

**Comment by lam3lka** [comment]
I've found: http://www.motorcyclespecs.co.za/Gallery%20B/Husaberg%20FE%20390%20Enduro%20%2010.jpg 
It's from different perspective. Do we want it?

**Comment by michalmikolajczyk** [comment]
Yes, I think that one's fine :)
