### ISSUE TITLE
handle hourly rentals

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#158]
As a user
On offer view, for bikes rented by the hour,
I would like to only choose a single day
and also choose the starting time
and the count of hours 
to book the motorcycle

**Comment by jonzee** [comment]
ok, I'm gonna use `material-ui` `datepicker` and `timepicker` (for hour), what should I use for `count of hours`? select list with fixed number of hours (how big interval?) or something else?

**Comment by michalmikolajczyk** [comment]
yep, a select list for 1, 2, 3 or 5 hours.

**Comment by jonzee** [comment]
@michalmikolajczyk How about price? It should be the different for all intervals or fixed?

**Comment by michalmikolajczyk** [comment]
@jonzee 
1. let's do a simple solution now. If it's easy to have different prices, please let us know.
2. let's do an hourly interval please
3. nope. Can we attach a price to that? i.e. modify the booking price (like an option with the offer, or a suboffer)

**Comment by jonzee** [comment]
1. Simple version is ready, it's not difficult to add different price for different intervals (we have to discuss how to express the difference - in percents? in fixed price? in fractions?)
2. Done.
3. I need more details how should this work.

**Comment by michalmikolajczyk** [comment]
re: 3.
Try and (1) spec out a few user stories, then (2) think of all the software components required, then (3) describe a plan for implementation.

**Comment by jonzee** [comment]
I created new issue #168 with equipment feature
