### ISSUE TITLE
time picker fixes

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#162]
- [x] please only show the widget for the hours, not the minutes (the interval is 1h)
- [x] I am not sure about the am / pm option, it's not popular in Poland. Please advise. I like the widget, but perhaps it's overkill to handle just the hours?
- [x] let's move the number of hours select field ABOVE the time picker. Or maybe to the side, like:
```
Meet up at <selectbox>, Ride for <selectbox> hours
```
or different style, e.g.
```
Ride for 2 hours, starting at 14:00
```

**Comment by jonzee** [comment]
done in #167

**Comment by michalmikolajczyk** [comment]
nicely done
