### ISSUE TITLE
display location and distance on the cards

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#164]
As a user on the offers list, 
I want to see the locations of the motorcycles, on the cards (bottom, 3rd line of text)
in the form of the name of the city (or other), where it is located,
like this:
```
Bangkok
```

As a user on the offers list,
If I agreed to share my location with the app,
I want to see my distance from the motorcycles,
displayed next to the name of their location city, after a comma,
like this:
```
Milano, 377 km
```

**Comment by lam3lka** [comment]
@jonzee location is already saved in our datebase. You just need to add information to 'coord' field - but you know it better than me ;)

**Comment by michalmikolajczyk** [comment]
No, we can't generate that info in the fly. If we only save the coordinates in the db then we should also store at least the name of the city, where it's located. The distance needs to be dynamic of course.

**Comment by jonzee** [comment]
@michalmikolajczyk this task needs upgrade the database, for now we don't store city of the offer,  other parts of task (displaying location & share location) are rather simple.

**Comment by michalmikolajczyk** [comment]
@jonzee let's update the db then? This is a very important feature, set as priority.

**Comment by jonzee** [comment]
@michalmikolajczyk ok, I can do it "manually" as I did before, or I can wait for migration flow, what you think?

**Comment by michalmikolajczyk** [comment]
@jonzee unless the migration flow is a blocker, this task has a higher priority. If the outcomes (products) of the planned automated migration flow, and the manual flow, are the same, then use the solution that takes the least time and has a stable (predictable) process.

**Comment by michalmikolajczyk** [comment]
👍
