### ISSUE TITLE
not visible offer details

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#165]
@jonzee w pierwszych ofertach wyświetlają się szczegóły na temat motocykli np. tutaj: 
https://www.vikinggarage.com/offer/5/yamaha-tricity-125-2016-warsaw

w kolejnych już nie ma tych informacji, a są wprowadzone w bazie danych np.: https://www.vikinggarage.com/offer/13/yamaha-tricity-125-2016-gdansk 
https://www.vikinggarage.com/offer/50/yamaha-R1-rn32-wroclaw

@michalmikolajczyk prośba o PRIORITY

**Comment by jonzee** [comment]
@lam3lka trzeba uzupełnić tabelę `offeritems`, w kolumnie `offerType` wpisać `motorcycle`, w kolumnie `offerId` wpisać `id` oferty, a w kolumnie `itemId` wpisać numer `id` motocykla (z tabeli `motorcycles`), nie trzeba przepisywać na nowo wierszy w tabeli `motorcycle`, jeśli motocykle nie różnią się parametrami można użyć już istniejących motocykli

**Comment by jonzee** [comment]
@lam3lka done, checkout if fine and pls close the issue
