### ISSUE TITLE
improve offer loading UX

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#166]
Jako użytkownik
przechodząc z widoku głównego do widoku oferty
przez pierwsze dwie sekundy widzę ładującą się ofertę (brak zdjęcia i puste pola z informacjami o motocyklu).

**Comment by michalmikolajczyk** [comment]
jako użytkownik,
nawigując pomiędzy stronami,
nie chcę widzieć zmian wysokości strony
przed i po załadowaniu treści

(co trwa ułamek sekundy, ale jest widoczne)
