### ISSUE TITLE
Move logic to higher components in Search subviews

### ISSUE THREAD

**Issue by jonzee** [michalmikolajczyk/viking-garage-frontend#174]

**Comment by jonzee** [comment]
done in https://github.com/michalmikolajczyk/viking-garage-frontend/pull/170/commits/9860938c3c0e39185b001196722657bba4abccae

**Comment by michalmikolajczyk** [comment]
in general, keep the logic in container components, and try to make the presentational components pure functions.

Apply those rules only to the components you are currently working upon (including fixes). Please do not apply the solution throughout the app.

**Comment by jonzee** [comment]
ok, I updated components in Search (I'm working on search bar currently) https://github.com/michalmikolajczyk/viking-garage-frontend/pull/170/commits/fd025f169dd35ce5bfbb26d092d06f94e0264712
