### ISSUE TITLE
Create language and currency selection

### ISSUE THREAD

**Issue by jonzee** [michalmikolajczyk/viking-garage-frontend#175]
As an user I want to pick up from app bar menu language and currency.
- [x] add buttons `Language` to menu
- [x] add nested menu with language `pl/en`
- [x] save user settings in local storage (and load them back)

**Comment by michalmikolajczyk** [comment]
@jonzee please do not add a settings button

**Comment by michalmikolajczyk** [comment]
```
as a user,
I want to be able to set the language of the app,
on every view, directly from the app bar
```

```
as a user,
I want to be able to set the currency,
on every view, directly from the app bar
```

**Comment by jonzee** [comment]
I created pull request #176 with `language selection`, now I want to discuss the `currency selection`. For now currency is strictly connected with translations (so I have to rewrite some parts of code) and I would create a new `pr` with this feature.
Another thing is that I'm not sure where to add `currency` button. In desktop there are 5 buttons in menu, and I'm not sure if another long button (`Currency (USD)`) would be fine. I tried to use some icons (like `world_icon (PL)`) but it wasn't ok.
@michalmikolajczyk, @lam3lka what do you think?

**Comment by michalmikolajczyk** [comment]
> Chodziło mi o string z kodem języka "PL" gdzieś w app bar, np. Jako drugi element od prawej. Lub trzeci od prawej, bo drugim powinna być waluta. Można dać tak:
> ```<ikona> <string>```
```<flag> PL | <coins> PLN```
>Flaga ikonka ogólna, nie Polski

**Comment by jonzee** [comment]
ok, added to #176

**Comment by michalmikolajczyk** [comment]
ok.
- [ ] select box otwierany w dół
- [ ] wersja z ikonkami

<img width="1680" alt="screen shot 2017-07-27 at 1 07 34 pm" src="https://user-images.githubusercontent.com/1655227/28667994-373a1c84-72ce-11e7-8ac8-b28e084b40dd.png">

**Comment by michalmikolajczyk** [comment]
<img width="1680" alt="screen shot 2017-07-27 at 1 07 34 pm" src="https://user-images.githubusercontent.com/1655227/28668607-e9fce58e-72d0-11e7-8e6a-2dac20d267c0.png">

**Comment by jonzee** [comment]
added in #176

**Comment by michalmikolajczyk** [comment]
good work
