### ISSUE TITLE
Conventions: whitespace & arrow functions in tsx

### ISSUE THREAD

**Issue by jonzee** [michalmikolajczyk/viking-garage-frontend#20]
I made some research about two often issue from code review.
1. `whitespaces` in `tsx`
It's ok to create components with text children in new line. It seems that `tsx` remove whitespaces before and after text as described [here](http://andrewhfarmer.com/how-whitespace-works-in-jsx/), but sometimes I want to keep whitespace after text, in this case I'll use no-breaking space `&nbsp;` i.e. to keep `Hello World` with gap:
```
<div>
  Hello&nbsp;
  <div className="bold">World</div>
</div>
```

2. Sometimes I made arrow functions in tsx components. I found out that it has a bad influence on performance as described [here](http://stackoverflow.com/questions/36677733/why-jsx-props-should-not-use-arrow-functions), so I suggest to create components property with callbacks:
```
export default class Verify extends React.Component<any, any> {
  ...
  closeError = () => this.setState({ error: false })

  render() {
    return (
      <Error
        open={this.state.error}
        close={this.closeError}
      />
    );
  }
}
```
If you ok with this remarks I'll create `PR` with style fixes.

**Comment by michalmikolajczyk** [comment]
1. ok can we agree to keep text inline with the inline element, at least? It hurts my eyes.

2. let's not use arrow functions to define TSX class methods. Agreed. Is that what you had in mind?

**Comment by jonzee** [comment]
Ad 1. Ok, as you wish :)
Ad 2. I wrote sometimes shorts like this:
```
export default class Verify extends React.Component<any, any> {
  ...
  render() {
    return (
      <Error
        open={() => this.setState({ error: true })}
        close={() => this.setState({ error: false })}
      />
    );
  }
}
```
But I found out that's a bad influence on performance and it's better to define class method with `setState`, `bind` them in `constructor` and pass like this `open={this.openModal}` etc.

**Comment by michalmikolajczyk** [comment]
yessir
