### ISSUE TITLE
upper search is not working

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#201]
As a user
when I scroll the website and decide to use the upper search 
I can enter only 3 letters and I can't even delete them.

<img width="1428" alt="zrzut ekranu 2017-09-19 o 14 58 28" src="https://user-images.githubusercontent.com/28931514/30594366-0b600740-9d4e-11e7-91a2-44245df7a098.png">

**Comment by michalmikolajczyk** [comment]
please test here https://viking-garage-frontend-staging.herokuapp.com/

**Comment by lam3lka** [comment]
Checked. Well done.
