### ISSUE TITLE
Add newletter popup 

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#225]
As a user I want when I enter the website
I want to leave my e-mail to stay in touch with VIKING GARAGE updates

GDP: 
https://www.readmeta.com/

**Comment by lam3lka** [comment]
I can't see any popup on the website

**Comment by michalmikolajczyk** [comment]
you need to wait 5 seconds, in incognito (it only works once for every user)

**Comment by michalmikolajczyk** [comment]
<img width="1680" alt="screen shot 2018-01-14 at 9 39 22 am" src="https://user-images.githubusercontent.com/1655227/34914236-d9ebb93a-f90e-11e7-9bb2-c1a627a08275.png">
