### ISSUE TITLE
Add info about Indiegogo

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#226]
As a user I want to see different VIKING GARAGE activities such as Indiegogo campaign

Still not sure if we should keep it as simple information (or banner) under the main photo "Ride better motorcycles" or we should also add it as a new tab in menu (as link do pre-launch website). 

Let's try both!

**Comment by michalmikolajczyk** [comment]
check it out on https://www.vikinggarage.com

**Comment by lam3lka** [comment]
@michalmikolajczyk mam wrażenie, że to logo Indiegogo trochę rozpikselowane - brałeś stąd: https://www.indiegogo.com/about/brand ?

**Comment by michalmikolajczyk** [comment]
tak
