### ISSUE TITLE
window['fetch'] for running tests

### ISSUE THREAD

**Issue by jonzee** [michalmikolajczyk/viking-garage-frontend#40]
There is a problem with `fetch` typings in tests environment. Application has its own typings for `fetch`, but tests need outer module that has conflicts with the app env.

**Comment by michalmikolajczyk** [comment]
ok, what do we do?

**Comment by michalmikolajczyk** [comment]
bump

**Comment by jonzee** [comment]
There is a conflict between `ts-node` that has typings for `fetch` (it runs app) and `ts-node/register` that runs tests (without typings). I can't just add typing for `fetch`, cause it makes conflict with `ts-node` typings. We can compile tests to pure js and then run all tests, but for me it's overkill. For now the simplest solution is cheating typescript with `window['fetch']`.

**Comment by michalmikolajczyk** [comment]
from what I remember, we decided to treat this as low priority. Perhaps globally implementing the `ts-node/register` solution, where there are no proprietary bindings, is a reasonable solution?

**Comment by jonzee** [comment]
done in #96, please check if this solution is ok, I didn't find anything better

**Comment by michalmikolajczyk** [comment]
no, you just created another global, that has nothing to do with pure functions

**Comment by michalmikolajczyk** [comment]
disregard the above comment, the polyfill should be fine
