### ISSUE TITLE
hide text-alternatives from HTML output

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#49]
please check how the scraper sees our site: http://www.seo-browser.com/index.php

https://viking-garage-frontend-s-pr-44.herokuapp.com/offer/2/honda-cb-125-1998-warsaw-poland this page actually has content from the server, but there is also a lot of trash like keyboard-arrow-down

**Comment by jonzee** [comment]
the `keyboard-arrow-down` and `date_range` comes from material icon, we can change them to fontawesome (they are empty)

**Comment by michalmikolajczyk** [comment]
please do

**Comment by michalmikolajczyk** [comment]
what alternatives are there?

**Comment by michalmikolajczyk** [comment]
bump

**Comment by jonzee** [comment]
didn't find other solution, removed all `material design icons`, added `font awesome` instead in #95

**Comment by michalmikolajczyk** [comment]
@jonzee siedzimy z @Malwix i @lam3lka i ogarniamy #95 zaraz recenzja

**Comment by michalmikolajczyk** [comment]
feedback: te ikony nie pasują do naszej otrej stylówy. są zbyt obłe, a nasz design ma ostre kanty. 

opcja 1:
powróćmy do poprzedniego zestawu ikon tylko naprawmy faktyczny błąd (SEO)

opcja 2:
@Malwix czy możesz zasugerować lub przygotować alternatywny zestaw ikon?

UWAGA, błąd #112 być może jest powiązany

**Comment by michalmikolajczyk** [comment]
let's go with option 1. from above.

- [ ] add a new higher order component for icons
- [ ] add support for alternatives for icons (strings)
- [ ] for server-side rendering, use the alternatives
- [ ] for client-side, use the icons

**Comment by jonzee** [comment]
done in #135, HOC wasn't the best idea, I used kinda of wrapper for `FontIcon`
