### ISSUE TITLE
Deliver data with initial HTML on homepage for SEO --> RAIDO

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#50]
please check how the scraper sees our site: http://www.seo-browser.com/index.php

there doesn't seem to be any offers, and we need them.
This is the home page for now. The offer pages seem to be ok, with minor bugs.

**Comment by jonzee** [comment]
done in #53

**Comment by michalmikolajczyk** [comment]
leaving this open till we close the PR

**Comment by jonzee** [comment]
ok, PR ready to review
