### ISSUE TITLE
add money.js

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#52]
from the document https://docs.google.com/document/d/1YCcqMSEi_BNPtJFibJUOjUVeLNWq9G_Fy0eStuo68T0/edit#

please use some currency exchange

**money.js**

**Comment by michalmikolajczyk** [comment]
http://openexchangerates.github.io/money.js/

**Comment by jonzee** [comment]
Added in PR #55, for now we have hardcoded exchange rate PLN to USD. `money.js` has payment API for that.

**Comment by michalmikolajczyk** [comment]
:pizza:
