### ISSUE TITLE
Lack of full name of location [tablet Samsung Galaxy 1024x768)]

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#65]
![screenshot_20170620-082618 1](https://user-images.githubusercontent.com/28931514/27328094-25ef1d06-55b1-11e7-8929-45b991e7894d.png)

**Comment by jonzee** [comment]
It's a `material-ui` component and I can't fix this in a simple way, @michalmikolajczyk said it's ok for now.
