### ISSUE TITLE
In calendar user can choose backwards dates [all devices]

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#69]
![screenshot_20170620-083002](https://user-images.githubusercontent.com/28931514/27328535-c188336e-55b2-11e7-8252-3b448e53bf75.png)

**Comment by jonzee** [comment]
done in #74

**Comment by lam3lka** [comment]
I don't see any changes, it's not working

**Comment by michalmikolajczyk** [comment]
moving discussion to PR #74
