### ISSUE TITLE
No padding in Internet Explorer browser

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#71]
![screenshot 2017-06-20 13-20-27](https://user-images.githubusercontent.com/28931514/27330893-893c1b98-55bb-11e7-8f07-9e1c5eaea637.jpg)

**Comment by jonzee** [comment]
@lam3lka version of IE?

**Comment by lam3lka** [comment]
11.0.14393.953

**Comment by jonzee** [comment]
fixed in #87, I pushed it on heroku dev

**Comment by lam3lka** [comment]
I think it's not enought. I'm enclosing some printscreens from m
![screenshot 2017-06-23 11-06-33](https://user-images.githubusercontent.com/28931514/27475088-2eabb6c0-5804-11e7-9ff7-1496d536c408.jpg)
![screenshot 2017-06-23 11-06-41](https://user-images.githubusercontent.com/28931514/27475097-33401992-5804-11e7-9086-ad1d0d30f601.jpg)

y IE view

**Comment by lam3lka** [comment]
it's even worse right now
![screenshot 2017-06-27 18-53-26](https://user-images.githubusercontent.com/28931514/27599737-ff63ade6-5b69-11e7-811c-29556e77f7d2.jpg)

**Comment by lam3lka** [comment]
Good job @jonzee !
