### ISSUE TITLE
enforce both code review and hallway testing

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#78]

**Comment by michalmikolajczyk** [comment]
zmieniamy flow, po recenzji kodu każdego PR i także manualnym przetestowaniu, przerzucam ten PR na @lam3lka lub @Malwix, następnie aplikacja jeszcze raz przechodzi manualny test.

Manualny test =
– test podstawowych funkcji aplikacji (flow od strony głównej do rezerwacji włącznie)
– test Issue, powiązanego z PR

@lam3lka przedstaw proszę flow zespołowi

**Comment by lam3lka** [comment]
@michalmikolajczyk ok

**Comment by lam3lka** [comment]
przedstawiłam flow zespołowi na spotkaniu w poniedziałek, flow jest w notatkach ze spotkania, Janek doda je również do dokumentu dotyczącego testowania aplikacji. 

Czy mozemy zamknąć Issue?

**Comment by michalmikolajczyk** [comment]
Jeszcze nie. @lam3lka czy możesz dodać treść do instrukcji testowania aplikacji? @jonzee ma jeszcze sporo zadań na głowie

**Comment by lam3lka** [comment]
@michalmikolajczyk jacha

**Comment by lam3lka** [comment]
tutaj: https://docs.google.com/a/vikinggarage.com/document/d/1E5Y8-Mz9saWihLC9pJJVJX5_tMmeUc_pjF2kZcX6KRg/edit?usp=sharing
