### ISSUE TITLE
configure api-prod as you please

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#79]
please configure api prod on heroku to your likings

**Comment by jonzee** [comment]
done, in #93 I added API production url

**Comment by michalmikolajczyk** [comment]
I made changes so `staging` is default, and we only have `dev` and `production` as exceptions

**Comment by michalmikolajczyk** [comment]
my changes are in `beta-fixes-comments` but they fail, would you like to take a look? I spent too much time on that already

**Comment by jonzee** [comment]
Ok, I applied changes in #93 and merged it

**Comment by michalmikolajczyk** [comment]
@jonzee please check the different env vars in API `dev` and `prod` and also this critical issue https://github.com/michalmikolajczyk/viking-garage-api/issues/28

**Comment by michalmikolajczyk** [comment]
@jonzee wtf?

**Comment by jonzee** [comment]
ok, env vars checked and correct with environment

**Comment by michalmikolajczyk** [comment]
cool. Please fill in the `app.json` file, set all our env vars to required, then configure all our apps on Heroku.

Let's treat `app.json` as the single source of truth for our env vars.

**Comment by michalmikolajczyk** [comment]
refer to `generators` in the `app.json` schema on Heroku docs for default sensitive values

**Comment by michalmikolajczyk** [comment]
configure the build scripts to:

- [ ] run the app in a new shell
- [ ] check `app.json` for required env vars
- [ ] cross-check the untracked `env` file OR available env vars with `app.json`
- [ ] load env vars from `env` file (optional, based on the point above)
- [ ] update README.md

**Comment by jonzee** [comment]
done in #126, as we spoke I didn't create new shell, just load & check env vars before running server

**Comment by michalmikolajczyk** [comment]
but why?

**Comment by jonzee** [comment]
for me it's simpler to keep loading & checking env vars in node, and exit process if something is wrong

**Comment by michalmikolajczyk** [comment]
@jonzee the production API is not configured correctly. The missing env vars are making the build fail.

**Comment by michalmikolajczyk** [comment]
https://docs.google.com/document/d/1DowF1WyghaL75qbuicF9NizXp8djcxDNq_fzqiWeVxw/edit

please expand the manual to cover those fields:

```
Link to your privacy policy *
```
```
What scopes does your app need to access? *
User data accessed through these apps must be approved
A full list of scopes can be seen here: https://developers.google.com/identity/protocols/googlescopes
```
```
List the specific ways your app will use each of the scopes you're testing *
Example: my app will use https://www.googleapis.com/auth/calendar.readonly to show a user's calendar data on the scheduling screen of my app.
```

**Comment by jonzee** [comment]
@michalmikolajczyk production configured due the newest api version (master)
