### ISSUE TITLE
routing error on mobile

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#82]
when navigating between views, the data is not filled in until manual page reload. Checked on iPhone

**Comment by jonzee** [comment]
I tried this on IPhone and routing worked (check for menu routes), perhaps loading offer take some time, I added kind of loading page for mobile view (in #87), but I'm still waiting for design from Malwa.

**Comment by michalmikolajczyk** [comment]
@jonzee nope, this is not acceptable. Even if it does work (and on my iPhone it does not work 10/10 times), the response from the API is over 10 s for a simple offer.

This is the highest priority.

**Comment by michalmikolajczyk** [comment]
<img width="1680" alt="screen shot 2017-06-24 at 2 55 29 am" src="https://user-images.githubusercontent.com/1655227/27504470-1b351da8-588a-11e7-9d3f-3a5ecdeb9326.png">

**Comment by jonzee** [comment]
Done in #93 (there is no `fetch` in old Safari and that was the problem)
