### ISSUE TITLE
search bar on desktop?

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#86]
what do we want to do with the empty space? I though it would initiate when user scroll below the search form below the VIKING GARAGE header. How do you see that?

**Comment by lam3lka** [comment]
I agree - user could use it to search location or motorcycle name

**Comment by jonzee** [comment]
Ok, we can do that, I need flow to understand what happens when user click on search in detail view etc. (and if we want to show other filters in detail view), i think it should take 4-6 hour to add search bar, cause I have to restructure some parts of code.

**Comment by lam3lka** [comment]
@michalmikolajczyk we agreed during our hangout 2 weeks ago that you will be responsible for writing a user story/ flow. Could you prepare it? I think I can learn it easly from gcp

**Comment by michalmikolajczyk** [comment]
```
As a user on a mobile device,
I would like to see the search bar at the top of the screen,
also when I scroll down
```

```
As a user on any device,
when I click in the search bar,
and input characters,
I would like to see results from a full-text database search (any text),
and also the results from Google places,
all sorted by highest search accuracy
```

So, two sources, essentially. We should not do operations on large sets, or do them in another process (e.g. web worker)

**Comment by michalmikolajczyk** [comment]
@lam3lka please check

a full-text search is basically a search through the whole content of the documents.

**Comment by michalmikolajczyk** [comment]
somehow related to #103

**Comment by jonzee** [comment]
Before review #170, pr needs some updates
- [ ] #171 
- [ ] #172 
- [ ] #173 
- [ ] #174

**Comment by michalmikolajczyk** [comment]
@jonzee please update with the pair session comments in mind and rebase

**Comment by jonzee** [comment]
@michalmikolajczyk done

**Comment by michalmikolajczyk** [comment]
@lam3lka please test this app: https://viking-garage-frontend--pr-170.herokuapp.com/

**Comment by lam3lka** [comment]
daję okejkę. Wszystko mi śmiga
