### ISSUE TITLE
Lack of margins

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#90]
![19416098_1543267509058378_2091815366_n](https://user-images.githubusercontent.com/28931514/27509696-e3b7c6b8-5902-11e7-9374-ce83b4443730.jpg)

**Comment by jonzee** [comment]
Checkout `dev`, on mobile there are no margins (checkout design), but there were other error (right-side margin on some devices, I fixed it)
