### ISSUE TITLE
Problem with footer - in offer view (iPhone 6)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#91]
![19477968_1543267495725046_366647137_n](https://user-images.githubusercontent.com/28931514/27509716-45f84190-5903-11e7-9d26-9c904f5d0fee.jpg)

**Comment by jonzee** [comment]
I removed floating button in #93, we have to add normal button somewhere on website, @lam3lka please tell me where do you thing button should be.

**Comment by lam3lka** [comment]
I have no idea guys, I can't imagine function of normal button somewhere on website as a chat. Do you know any good examples of using normal button  as chat on other webistes?
