### ISSUE TITLE
Live chat is not working (iPhone 6)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#92]
Cannot use Live Chat on mobile. 
![19441390_1543314972386965_2015490428_n](https://user-images.githubusercontent.com/28931514/27509748-eea6b614-5903-11e7-8306-31dff89f139e.jpg)

**Comment by jonzee** [comment]
Did you checkout this on private mode? It's problem with livechat, not an application

**Comment by lam3lka** [comment]
idn. Right know I can't check it because there is no livechat on our website

**Comment by jonzee** [comment]
ok, we will check this when we go back to livechat
