### ISSUE TITLE
Chrome browser can not find vikinggarage.com (desktop, Microsoft Windows 10 Home, version 10.0. 14393)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#97]
![screenshot 2017-06-27 19-06-52](https://user-images.githubusercontent.com/28931514/27600403-1c0abff0-5b6c-11e7-9bca-00b88f681e7b.jpg)

**Comment by michalmikolajczyk** [comment]
closing for now. I improved the redirects, currently even the weakest redirect `http://vikinggarage.com => https://www.vikinggarage.com` works as expected
