### ISSUE TITLE
Can we make this pop-up without scrolling? (iPhone 6)

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#98]
![bc0e63d73f4c72eb789d0530435e745f](https://user-images.githubusercontent.com/28931514/27608427-d58c158a-5b87-11e7-88dd-0be2d786f71e.jpg)

**Comment by jonzee** [comment]
@lam3lka I fixed this pop-up on mobile (and desktop), now they are full screen, ask Malwa if it's alright.
